name: note_server_api
description: A simple note server API using Dart.
version: 1.0.0

environment:
  sdk: ">=2.18.0 <3.0.0" # Điều chỉnh SDK về phiên bản hợp lệ

dependencies:
  shelf: ^1.3.0
  shelf_router: ^1.1.0
  postgres: ^2.5.0
  shelf_cors: ^1.2.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
